import Foundation
import ForgeFilesystemProtocol

/// One bounded health observation made through the privileged filesystem daemon.
/// The session identifier is generated by the caller and is intentionally reused
/// by the pre- and post-checks so qualification tooling can reject mixed sessions.
public struct SecureFilesystemQualificationHealthSnapshot: Sendable, Equatable {
    public enum Check: String, Sendable {
        case preHealth = "pre_health"
        case postHealth = "post_health"
    }

    public let schemaVersion: Int
    public let check: Check
    public let sessionID: String
    public let ok: Bool
    public let code: String
    public let message: String
    public let serviceIdentityVerified: Bool
    public let connectionReused: Bool
    public let protocolVersion: Int?
    public let productVersion: String?
    public let serviceIdentifier: String?
    public let effectiveUserIdentifier: UInt32?
    public let codeDirectoryHash: String?
    public let allowedCodeDirectoryHashes: [String]
    public let statusDurabilityConfirmed: Bool

    public var jsonObject: [String: Any] {
        var object: [String: Any] = [
            "schema_version": schemaVersion,
            "event": check.rawValue,
            "session_id": sessionID,
            "ok": ok,
            "code": code,
            "message": message,
            "service_identity_verified": serviceIdentityVerified,
            "connection_reused": connectionReused,
            "allowed_code_directory_hashes": allowedCodeDirectoryHashes,
            "status_durability_confirmed": statusDurabilityConfirmed,
        ]
        if let protocolVersion { object["protocol_version"] = protocolVersion }
        if let productVersion { object["product_version"] = productVersion }
        if let serviceIdentifier { object["service_identifier"] = serviceIdentifier }
        if let effectiveUserIdentifier {
            object["effective_uid"] = Int(effectiveUserIdentifier)
        }
        if let codeDirectoryHash { object["code_directory_hash"] = codeDirectoryHash }
        return object
    }
}

private enum SecureFilesystemQualificationHealthCode {
    static let invalidState = "secure_filesystem_health_invalid_state"
    static let invalidStatus = "secure_filesystem_health_status_invalid"
}

/// This deliberately narrower client interface does not expose a root descriptor
/// or any mutation selector to the qualification probe.
@objc private protocol SecureFilesystemQualificationHealthXPC {
    func serviceInfo(withReply reply: @escaping (ForgeFilesystemServiceInfo) -> Void)
    func status(withReply reply: @escaping (ForgeFilesystemResponse) -> Void)
}

protocol SecureFilesystemQualificationHealthConnection: AnyObject {
    func activate()
    func requestServiceInfo(_ reply: @escaping (ForgeFilesystemServiceInfo) -> Void)
    func requestStatus(_ reply: @escaping (ForgeFilesystemResponse) -> Void)
    func invalidate()
}

typealias SecureFilesystemQualificationHealthConnectionFactory = (
    _ signingRequirement: String,
    _ failure: @escaping (_ code: String, _ message: String) -> Void
) -> any SecureFilesystemQualificationHealthConnection

typealias SecureFilesystemQualificationMonotonicClock = @Sendable () -> UInt64

private final class XPCSecureFilesystemQualificationHealthConnection:
    SecureFilesystemQualificationHealthConnection
{
    private let connection: NSXPCConnection
    private let failure: (String, String) -> Void

    init(
        signingRequirement: String,
        failure: @escaping (String, String) -> Void
    ) {
        self.failure = failure
        connection = NSXPCConnection(
            machServiceName: ForgeFilesystemProtocolConstants.serviceName,
            options: .privileged
        )
        connection.remoteObjectInterface = NSXPCInterface(
            with: SecureFilesystemQualificationHealthXPC.self
        )
        connection.setCodeSigningRequirement(signingRequirement)
        connection.interruptionHandler = { [failure] in
            failure(
                ForgeFilesystemErrorCode.helperUnavailable,
                "Secure filesystem health connection was interrupted"
            )
        }
        connection.invalidationHandler = { [failure] in
            failure(
                ForgeFilesystemErrorCode.helperUnavailable,
                "Secure filesystem health connection was invalidated"
            )
        }
    }

    func activate() {
        connection.activate()
    }

    func requestServiceInfo(_ reply: @escaping (ForgeFilesystemServiceInfo) -> Void) {
        guard let proxy = remoteProxy() else { return }
        proxy.serviceInfo(withReply: reply)
    }

    func requestStatus(_ reply: @escaping (ForgeFilesystemResponse) -> Void) {
        guard let proxy = remoteProxy() else { return }
        proxy.status(withReply: reply)
    }

    func invalidate() {
        connection.invalidate()
    }

    private func remoteProxy() -> SecureFilesystemQualificationHealthXPC? {
        guard let proxy = connection.remoteObjectProxyWithErrorHandler({ [failure] error in
            let description = error.localizedDescription.lowercased()
            let identityFailure = description.contains("code sign")
                || description.contains("requirement")
            failure(
                identityFailure
                    ? ForgeFilesystemErrorCode.helperIdentityMismatch
                    : ForgeFilesystemErrorCode.helperUnavailable,
                identityFailure
                    ? "Secure filesystem health peer identity validation failed"
                    : "Secure filesystem health connection failed"
            )
        }) as? SecureFilesystemQualificationHealthXPC else {
            failure(
                ForgeFilesystemErrorCode.helperUnavailable,
                "Secure filesystem health proxy is unavailable"
            )
            return nil
        }
        return proxy
    }
}

struct SecureFilesystemQualificationHealthStateMachine {
    enum Phase: Equatable {
        case idle
        case awaitingIdentity
        case awaitingPreStatus
        case readyForPostCheck
        case awaitingPostStatus
        case postCheckComplete
        case failed
        case closed
    }

    enum ServiceInfoDisposition: Equatable {
        case requestStatus
        case completed
        case ignore
    }

    enum FailureDisposition: Equatable {
        case signalPreCheck
        case signalPostCheck
        case recordedForPostCheck
        case ignore
    }

    private(set) var phase: Phase = .idle
    private(set) var latestSnapshot: SecureFilesystemQualificationHealthSnapshot?
    let sessionID: String
    private var serviceInfo: ForgeFilesystemServiceInfo?
    private var allowedCodeDirectoryHashes: [String] = []
    private var preHealthSnapshot: SecureFilesystemQualificationHealthSnapshot?
    private var postHealthSnapshot: SecureFilesystemQualificationHealthSnapshot?
    private var preHealthDeadlineNanoseconds: UInt64?
    private var postHealthDeadlineNanoseconds: UInt64?

    init(sessionID: UUID = UUID()) {
        self.sessionID = sessionID.uuidString.lowercased()
    }

    mutating func beginPreCheck(deadlineNanoseconds: UInt64 = .max) -> Bool {
        guard phase == .idle else { return false }
        preHealthDeadlineNanoseconds = deadlineNanoseconds
        phase = .awaitingIdentity
        return true
    }

    mutating func receiveServiceInfo<S: Sequence>(
        _ information: ForgeFilesystemServiceInfo,
        allowedCodeDirectoryHashes: S,
        monotonicTimestampNanoseconds: UInt64 = DispatchTime.now().uptimeNanoseconds
    ) -> ServiceInfoDisposition where S.Element == String {
        guard phase == .awaitingIdentity else { return .ignore }
        guard let deadline = preHealthDeadlineNanoseconds,
              monotonicTimestampNanoseconds < deadline else {
            _ = timeout(check: .preHealth)
            return .completed
        }
        guard let normalizedAllowedHashes = ForgeFilesystemCodeIdentity
                .normalizedCodeDirectoryHashes(allowedCodeDirectoryHashes) else {
            record(snapshot(
                check: .preHealth,
                ok: false,
                code: ForgeFilesystemErrorCode.helperIdentityMismatch,
                message: "Secure filesystem service allowlist is invalid",
                serviceIdentityVerified: false,
                connectionReused: false,
                statusDurabilityConfirmed: false
            ))
            phase = .failed
            return .completed
        }
        self.allowedCodeDirectoryHashes = normalizedAllowedHashes
        guard information.matchesExpectedService(
            allowedCodeDirectoryHashes: normalizedAllowedHashes
        ) else {
            record(snapshot(
                check: .preHealth,
                ok: false,
                code: ForgeFilesystemErrorCode.helperIdentityMismatch,
                message: "Secure filesystem service version or runtime identity does not match",
                serviceIdentityVerified: false,
                connectionReused: false,
                statusDurabilityConfirmed: false
            ))
            phase = .failed
            return .completed
        }
        serviceInfo = information
        phase = .awaitingPreStatus
        return .requestStatus
    }

    @discardableResult
    mutating func receiveStatus(
        _ response: ForgeFilesystemResponse,
        monotonicTimestampNanoseconds: UInt64 = DispatchTime.now().uptimeNanoseconds
    ) -> Bool {
        let check: SecureFilesystemQualificationHealthSnapshot.Check
        let connectionReused: Bool
        let successfulPhase: Phase
        let deadline: UInt64?
        switch phase {
        case .awaitingPreStatus:
            check = .preHealth
            connectionReused = false
            successfulPhase = .readyForPostCheck
            deadline = preHealthDeadlineNanoseconds
        case .awaitingPostStatus:
            check = .postHealth
            connectionReused = true
            successfulPhase = .postCheckComplete
            deadline = postHealthDeadlineNanoseconds
        default:
            return false
        }
        guard let deadline, monotonicTimestampNanoseconds < deadline else {
            _ = timeout(check: check)
            return true
        }

        let statusIsValid = response.validationError() == nil
            && response.ok
            && response.code == "ok"
            && !response.committed
            && response.durabilityConfirmed
            && response.recoveryTransactionID == nil
            && !response.acknowledgementRequired
        record(snapshot(
            check: check,
            ok: statusIsValid,
            code: statusIsValid ? response.code : SecureFilesystemQualificationHealthCode.invalidStatus,
            message: statusIsValid
                ? response.message
                : "Secure filesystem service returned an invalid health status",
            serviceIdentityVerified: serviceInfo != nil,
            connectionReused: connectionReused,
            statusDurabilityConfirmed: response.durabilityConfirmed
        ))
        phase = statusIsValid ? successfulPhase : .failed
        return true
    }

    mutating func beginPostCheck(deadlineNanoseconds: UInt64 = .max) -> Bool {
        guard phase == .readyForPostCheck else { return false }
        postHealthDeadlineNanoseconds = deadlineNanoseconds
        phase = .awaitingPostStatus
        return true
    }

    @discardableResult
    mutating func fail(code: String, message: String) -> FailureDisposition {
        let disposition: FailureDisposition
        let check: SecureFilesystemQualificationHealthSnapshot.Check
        let reused: Bool
        switch phase {
        case .awaitingIdentity, .awaitingPreStatus:
            disposition = .signalPreCheck
            check = .preHealth
            reused = false
        case .readyForPostCheck:
            disposition = .recordedForPostCheck
            check = .postHealth
            reused = true
        case .awaitingPostStatus:
            disposition = .signalPostCheck
            check = .postHealth
            reused = true
        default:
            return .ignore
        }
        record(snapshot(
            check: check,
            ok: false,
            code: code,
            message: message,
            serviceIdentityVerified: serviceInfo != nil,
            connectionReused: reused,
            statusDurabilityConfirmed: false
        ))
        phase = .failed
        return disposition
    }

    @discardableResult
    mutating func timeout(
        check: SecureFilesystemQualificationHealthSnapshot.Check
    ) -> FailureDisposition {
        switch (check, phase) {
        case (.preHealth, .awaitingIdentity), (.preHealth, .awaitingPreStatus),
             (.postHealth, .awaitingPostStatus):
            return fail(
                code: ForgeFilesystemErrorCode.helperUnavailable,
                message: check == .preHealth
                    ? "Secure filesystem health pre-check timed out"
                    : "Secure filesystem health post-check timed out"
            )
        default:
            return .ignore
        }
    }

    mutating func invalidStateSnapshot(
        check: SecureFilesystemQualificationHealthSnapshot.Check
    ) -> SecureFilesystemQualificationHealthSnapshot {
        snapshot(
            check: check,
            ok: false,
            code: SecureFilesystemQualificationHealthCode.invalidState,
            message: "Secure filesystem health session is not in the required state",
            serviceIdentityVerified: serviceInfo != nil,
            connectionReused: check == .postHealth,
            statusDurabilityConfirmed: false
        )
    }

    mutating func close() {
        phase = .closed
    }

    func storedSnapshot(
        for check: SecureFilesystemQualificationHealthSnapshot.Check
    ) -> SecureFilesystemQualificationHealthSnapshot? {
        switch check {
        case .preHealth: preHealthSnapshot
        case .postHealth: postHealthSnapshot
        }
    }

    private mutating func record(
        _ snapshot: SecureFilesystemQualificationHealthSnapshot
    ) {
        latestSnapshot = snapshot
        switch snapshot.check {
        case .preHealth: preHealthSnapshot = snapshot
        case .postHealth: postHealthSnapshot = snapshot
        }
    }

    private func snapshot(
        check: SecureFilesystemQualificationHealthSnapshot.Check,
        ok: Bool,
        code: String,
        message: String,
        serviceIdentityVerified: Bool,
        connectionReused: Bool,
        statusDurabilityConfirmed: Bool
    ) -> SecureFilesystemQualificationHealthSnapshot {
        SecureFilesystemQualificationHealthSnapshot(
            schemaVersion: 1,
            check: check,
            sessionID: sessionID,
            ok: ok,
            code: String(code.prefix(128)),
            message: String(message.prefix(1_024)),
            serviceIdentityVerified: serviceIdentityVerified,
            connectionReused: connectionReused,
            protocolVersion: serviceInfo?.protocolVersion,
            productVersion: serviceInfo?.productVersion,
            serviceIdentifier: serviceInfo?.serviceIdentifier,
            effectiveUserIdentifier: serviceInfo?.effectiveUserIdentifier,
            codeDirectoryHash: serviceInfo?.codeDirectoryHash,
            allowedCodeDirectoryHashes: allowedCodeDirectoryHashes,
            statusDurabilityConfirmed: statusDurabilityConfirmed
        )
    }
}

private final class SecureFilesystemQualificationHealthCoordinator: @unchecked Sendable {
    private let lock = NSRecursiveLock()
    private let preCheckSignal = DispatchSemaphore(value: 0)
    private let postCheckSignal = DispatchSemaphore(value: 0)
    private var machine: SecureFilesystemQualificationHealthStateMachine

    init(sessionID: UUID = UUID()) {
        machine = SecureFilesystemQualificationHealthStateMachine(sessionID: sessionID)
    }

    var sessionID: String {
        lock.lock()
        defer { lock.unlock() }
        return machine.sessionID
    }

    func beginPreCheck(deadlineNanoseconds: UInt64) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return machine.beginPreCheck(deadlineNanoseconds: deadlineNanoseconds)
    }

    func receiveServiceInfo(
        _ information: ForgeFilesystemServiceInfo,
        allowedCodeDirectoryHashes: [String],
        monotonicTimestampNanoseconds: UInt64,
        requestStatus: () -> Void
    ) {
        lock.lock()
        let disposition = machine.receiveServiceInfo(
            information,
            allowedCodeDirectoryHashes: allowedCodeDirectoryHashes,
            monotonicTimestampNanoseconds: monotonicTimestampNanoseconds
        )
        if disposition == .requestStatus { requestStatus() }
        lock.unlock()
        if disposition == .completed { preCheckSignal.signal() }
    }

    func receiveStatus(
        _ response: ForgeFilesystemResponse,
        monotonicTimestampNanoseconds: UInt64
    ) {
        lock.lock()
        let phase = machine.phase
        let accepted = machine.receiveStatus(
            response,
            monotonicTimestampNanoseconds: monotonicTimestampNanoseconds
        )
        lock.unlock()
        guard accepted else { return }
        switch phase {
        case .awaitingPreStatus: preCheckSignal.signal()
        case .awaitingPostStatus: postCheckSignal.signal()
        default: break
        }
    }

    func beginPostCheck(deadlineNanoseconds: UInt64) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return machine.beginPostCheck(deadlineNanoseconds: deadlineNanoseconds)
    }

    func fail(code: String, message: String) {
        lock.lock()
        let disposition = machine.fail(code: code, message: message)
        lock.unlock()
        switch disposition {
        case .signalPreCheck: preCheckSignal.signal()
        case .signalPostCheck: postCheckSignal.signal()
        case .recordedForPostCheck, .ignore: break
        }
    }

    func timeout(
        check: SecureFilesystemQualificationHealthSnapshot.Check
    ) {
        lock.lock()
        let disposition = machine.timeout(check: check)
        lock.unlock()
        switch disposition {
        case .signalPreCheck: preCheckSignal.signal()
        case .signalPostCheck: postCheckSignal.signal()
        case .recordedForPostCheck, .ignore: break
        }
    }

    func waitForPreCheck(until deadline: DispatchTime) -> DispatchTimeoutResult {
        preCheckSignal.wait(timeout: deadline)
    }

    func waitForPostCheck(until deadline: DispatchTime) -> DispatchTimeoutResult {
        postCheckSignal.wait(timeout: deadline)
    }

    func snapshot(
        for check: SecureFilesystemQualificationHealthSnapshot.Check
    ) -> SecureFilesystemQualificationHealthSnapshot {
        lock.lock()
        defer { lock.unlock() }
        return machine.storedSnapshot(for: check)
            ?? machine.invalidStateSnapshot(check: check)
    }

    func invalidStateSnapshot(
        for check: SecureFilesystemQualificationHealthSnapshot.Check
    ) -> SecureFilesystemQualificationHealthSnapshot {
        lock.lock()
        defer { lock.unlock() }
        return machine.invalidStateSnapshot(check: check)
    }

    func close() {
        lock.lock()
        machine.close()
        lock.unlock()
    }
}

/// A qualification-only, non-mutating health session. `open` authenticates the
/// daemon from caller-sealed CDHashes and completes the pre-check. `postCheck`
/// may be called exactly once and reuses the same live XPC connection.
public final class SecureFilesystemQualificationHealthSession: @unchecked Sendable {
    private struct PeerConfiguration {
        let allowedCodeDirectoryHashes: [String]
        let signingRequirement: String
    }

    private let operationLock = NSLock()
    private let coordinator: SecureFilesystemQualificationHealthCoordinator
    private let peerConfiguration: () -> PeerConfiguration?
    private let connectionFactory: SecureFilesystemQualificationHealthConnectionFactory
    private let monotonicNow: SecureFilesystemQualificationMonotonicClock
    private var connection: (any SecureFilesystemQualificationHealthConnection)?

    public convenience init() {
        self.init(
            peerConfiguration: {
                guard let securedInfo = ForgeFilesystemCodeIdentity
                        .currentSecuredInfoDictionary(),
                      let hashes = ForgeFilesystemCodeIdentity
                        .daemonCodeDirectoryHashes(inSecuredInfoDictionary: securedInfo),
                      let requirement = ForgeFilesystemProtocolConstants
                        .requiredDaemonCodeSigningRequirement(codeDirectoryHashes: hashes) else {
                    return nil
                }
                return PeerConfiguration(
                    allowedCodeDirectoryHashes: hashes,
                    signingRequirement: requirement
                )
            },
            connectionFactory: { requirement, failure in
                XPCSecureFilesystemQualificationHealthConnection(
                    signingRequirement: requirement,
                    failure: failure
                )
            },
            monotonicNow: { DispatchTime.now().uptimeNanoseconds }
        )
    }

    init(
        sessionID: UUID = UUID(),
        allowedCodeDirectoryHashes: [String],
        signingRequirement: String = "test requirement",
        connectionFactory: @escaping SecureFilesystemQualificationHealthConnectionFactory,
        monotonicNow: @escaping SecureFilesystemQualificationMonotonicClock = {
            DispatchTime.now().uptimeNanoseconds
        }
    ) {
        self.coordinator = SecureFilesystemQualificationHealthCoordinator(
            sessionID: sessionID
        )
        self.peerConfiguration = {
            PeerConfiguration(
                allowedCodeDirectoryHashes: allowedCodeDirectoryHashes,
                signingRequirement: signingRequirement
            )
        }
        self.connectionFactory = connectionFactory
        self.monotonicNow = monotonicNow
    }

    private init(
        sessionID: UUID = UUID(),
        peerConfiguration: @escaping () -> PeerConfiguration?,
        connectionFactory: @escaping SecureFilesystemQualificationHealthConnectionFactory,
        monotonicNow: @escaping SecureFilesystemQualificationMonotonicClock
    ) {
        self.coordinator = SecureFilesystemQualificationHealthCoordinator(
            sessionID: sessionID
        )
        self.peerConfiguration = peerConfiguration
        self.connectionFactory = connectionFactory
        self.monotonicNow = monotonicNow
    }

    public func open(timeout: TimeInterval = 5) -> SecureFilesystemQualificationHealthSnapshot {
        operationLock.lock()
        defer { operationLock.unlock() }
        guard connection == nil else {
            return coordinator.snapshot(for: .preHealth)
        }
        let deadline = makeDeadline(timeout: timeout)
        guard coordinator.beginPreCheck(
            deadlineNanoseconds: deadline.uptimeNanoseconds
        ) else {
            return coordinator.snapshot(for: .preHealth)
        }
        guard let configuration = peerConfiguration() else {
            coordinator.fail(
                code: ForgeFilesystemErrorCode.helperIdentityMismatch,
                message: "The packaged secure filesystem service identity is unavailable"
            )
            return coordinator.snapshot(for: .preHealth)
        }
        let connection = connectionFactory(
            configuration.signingRequirement,
            { [coordinator] code, message in
                coordinator.fail(code: code, message: message)
            }
        )
        self.connection = connection
        connection.activate()
        let monotonicNow = self.monotonicNow
        connection.requestServiceInfo { [coordinator] information in
            coordinator.receiveServiceInfo(
                information,
                allowedCodeDirectoryHashes: configuration.allowedCodeDirectoryHashes,
                monotonicTimestampNanoseconds: monotonicNow()
            ) {
                connection.requestStatus { [coordinator] response in
                    coordinator.receiveStatus(
                        response,
                        monotonicTimestampNanoseconds: monotonicNow()
                    )
                }
            }
        }
        if coordinator.waitForPreCheck(until: deadline) == .timedOut {
            coordinator.timeout(check: .preHealth)
        }
        let snapshot = coordinator.snapshot(for: .preHealth)
        if !snapshot.ok {
            connection.invalidate()
            self.connection = nil
        }
        return snapshot
    }

    public func postCheck(
        timeout: TimeInterval = 5
    ) -> SecureFilesystemQualificationHealthSnapshot {
        operationLock.lock()
        defer { operationLock.unlock() }
        guard let connection else {
            return coordinator.invalidStateSnapshot(for: .postHealth)
        }
        let deadline = makeDeadline(timeout: timeout)
        let began = coordinator.beginPostCheck(
            deadlineNanoseconds: deadline.uptimeNanoseconds
        )
        guard began else {
            return coordinator.snapshot(for: .postHealth)
        }
        let monotonicNow = self.monotonicNow
        connection.requestStatus { [coordinator] response in
            coordinator.receiveStatus(
                response,
                monotonicTimestampNanoseconds: monotonicNow()
            )
        }
        if coordinator.waitForPostCheck(until: deadline) == .timedOut {
            coordinator.timeout(check: .postHealth)
        }
        return coordinator.snapshot(for: .postHealth)
    }

    public func close() {
        operationLock.lock()
        let existingConnection = connection
        connection = nil
        coordinator.close()
        operationLock.unlock()
        existingConnection?.invalidate()
    }

    deinit {
        connection?.invalidate()
    }

    private func makeDeadline(timeout: TimeInterval) -> DispatchTime {
        let boundedTimeout = max(0.001, min(10, timeout))
        let intervalNanoseconds = UInt64(boundedTimeout * 1_000_000_000)
        let now = monotonicNow()
        let value = now.addingReportingOverflow(intervalNanoseconds)
        return DispatchTime(
            uptimeNanoseconds: value.overflow ? UInt64.max : value.partialValue
        )
    }
}
